#!/bin/bash
  
EXPECTED_ARGS=4
E_BADARGS=65

if [ $# == $EXPECTED_ARGS ]
then

  MYSQL=`which mysql`
  
  Q1="CREATE DATABASE IF NOT EXISTS $2;"
  Q2="GRANT USAGE ON *.* TO $3@localhost IDENTIFIED BY '$4';"
  Q3="GRANT ALL PRIVILEGES ON $2.* TO $3@localhost;"
  Q4="FLUSH PRIVILEGES;"

  Q5="USE $2;"
  CREATE_TABLES=$(<createTables)

  W1="CREATE DATABASE IF NOT EXISTS $2_test;"
  W2="GRANT USAGE ON *.* TO $3@localhost IDENTIFIED BY '$4';"
  W3="GRANT ALL PRIVILEGES ON $2_test.* TO $3@localhost;"
  W4="FLUSH PRIVILEGES;"

  W5="USE $2_test;"

  INSERT_DATA=$(<insertData)

  SQL1="${Q1}${Q2}${Q3}${Q4}${Q5}${CREATE_TABLES}"
  SQL2="${W1}${W2}${W3}${W4}${W5}${CREATE_TABLES}${INSERT_DATA}"
  SQL="${SQL1}${SQL2}"

  $MYSQL -u$3 -p$4 -e "$SQL"

  echo "Created: 
$2 
$2_test"

  echo "$2" > dbName

  S1="db.driver=com.mysql.jdbc.Driver"
  S2="db.database=jdbc:mysql://localhost:$1/$2"
  S3="db.database.test=jdbc:mysql://localhost:$1/$2_test"
  S4="db.user=$3"
  S5="db.password=$4"
  S6="db.database.test.size=5"

  echo "${S1}
${S2}
${S3}
${S4}
${S5}
${S6}" > database.properties

cp database.properties ../app-dao-jdbc/src/main/resources 
 
else
  echo "Error: Bad args. You need to have $EXPECTED_ARGS args: port, dbname, username, pwd"
  exit $E_BADARGS
fi
