#!/bin/bash
  
EXPECTED_ARGS=2
E_BADARGS=65

if [ $# == $EXPECTED_ARGS ]
then

  MYSQL=`which mysql`

  DB_NAME=$(<dbName)  

  SQL1="DROP DATABASE IF EXISTS ${DB_NAME};"
  SQL2="DROP DATABASE IF EXISTS ${DB_NAME}_test;"

  SQL=${SQL1}${SQL2}

  $MYSQL -u$1 -p$2 -e "$SQL"

  echo "Droped:
${DB_NAME}
${DB_NAME}_test"
  
else
  echo "Error: Bad args. You need to have ${EXPECTED_ARGS} args: <mysql user> <user's password>"

  exit $E_BADARGS
fi
